### ISSUE TITLE
Add webdav support for go-storage

### ISSUE THREAD

**Issue by Xuanwo** [beyondstorage/go-service-webdav#1]
## Description

[WebDAV](https://en.wikipedia.org/wiki/WebDAV) is a widely used protocol to transfer files, It's could nice to add support in go-storage.

## Roadmap

- [ ] Choose a well maintained WebDAV library
- [ ] Implement all interface that Storager required
- [ ] Setup integration tests
- [ ] Add docs in [site](https://github.com/aos-dev/site)
- [ ] Add examples in [example](https://github.com/aos-dev/go-storage-example)

**Comment by Xuanwo** [comment]
@hzeroto is responsible for this issue.
